### PR TITLE
Use Jest snapshots and sprinkle some esnext syntax

### PR DESCRIPTION
**Pull request by RichAyotte**
I think Jest snapshots are a good use case for this type of code generation.

My coding style is a bit unorthodox so comments are welcome on that. An eslint file would help if this is a concern.

Let me know if you'd like more PR like this.

### CODE REVIEW

**Comment by RichAyotte** [comment]
@stephenandrews I just noticed that you pushed some conflicting changes. I think snapshotting is like the compare that you're doing but easier to maintain.

**Comment by stephenandrews** [comment]
Ya I like the snapshots better, will overwrite with your work. Thanks :-)

**Comment by RichAyotte** [comment]
I'll rebase and resubmit shortly.

**Comment by stephenandrews** [comment]
It's fine, I resolved it :-)

**Comment by RichAyotte** [comment]
Great! Thanks!

**Comment by stephenandrews** [comment]
@RichAyotte In future, I want to expose the individual methods and run tests on them (it's not too hard to do), as well as refactor the codebase and update to ES >5. If you're interested in a paid position send me an email - stephen@teztech.io

**Pull request merged**
